version: '3.5'

services:
  api:
    container_name: cars-api
    restart: always
    build:
      args:
        PROJECT_NAME: cars
      context: .
      dockerfile: Dockerfile
    networks:
      - cars_net
    ports:
      - '8080:8080'
    environment:
      - APP_ENV=development
      - APP_ENDPOINT
      - PORT
    command: ./cars

networks:
  cars_net:
    name: cars_net
